# Model arguments
model_name_or_path: /home/xysun/models/deepseek-coder-33b-instruct
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: true

# LoRA arguments
use_peft: true
lora_r: 64
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj

# Data training arguments
dataset_mixer:
  train: /home/xysun/data/magicoder/data-oss_instruct-decontaminated_regen.jsonl
data_format: json
preprocessing_num_workers: 12
cache_dir: /home/xysun/data/cache_dir

# SFT trainer config
bf16: true
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 8
gradient_checkpointing: true
learning_rate: 2.0e-05
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 1280
max_steps: -1
num_train_epochs: 1
output_dir: /home/xysun/models/checkpoint/esp-deepseek-33b-v2
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: false
remove_unused_columns: true
report_to:
- tensorboard
save_strategy: "no"
save_total_limit: null
seed: 42
tf32: true
